services:
  db:
    image: mysql
    container_name: mysql_db
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: app_db
      MYSQL_USER: app_user
      MYSQL_PASSWORD: app_password
    ports:
      - "3307:3306"
    volumes:
      - ./data/init.sql:/docker-entrypoint-initdb.d/init.sql
    networks:
      - app_network

  api:
    build:
      context: ./api
    container_name: api
    environment:
      MYSQL_HOST: db
      MYSQL_PORT: 3306
      MYSQL_USER: app_user
      MYSQL_PASSWORD: app_password
      MYSQL_DATABASE: app_db
      GOOGLE_API_KEY: ${GOOGLE_API_KEY}
    ports:
      - "8080:8080"
    depends_on:
      - db
    networks:
      - app_network
    command: npm start

  frontend:
    build:
      context: ./app
    container_name: frontend
    ports:
      - "80:3000"
    networks:
      - app_network
    environment:
      - REACT_APP_GOOGLE_API_KEY=${GOOGLE_API_KEY}  
      - REACT_APP_API_URL=http://localhost:8080  
      - CHOKIDAR_USEPOLLING=true

networks:
  app_network:
    driver: bridge