services:
  db:
    image: mysql
    container_name: mysql_db
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: app_db
      MYSQL_USER: app_user
      MYSQL_PASSWORD: app_password
    ports:
      - "3307:3306"
    volumes:
      #- db_data:/var/lib/mysql
      - ./data/init.sql:/docker-entrypoint-initdb.d/init.sql
#volumes:
  #db_data:
